[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin: '*',
    Access-Control-Allow-Headers: 'Content-Type',
    Access-Control-Allow-Methods: 'GET, POST, PUT, DELETE'
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
